# Generated by Django 4.2.16 on 2026-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Client', models.CharField(blank=True, default='', max_length=255)),
                ('Contract_number', models.CharField(blank=True, default='', max_length=100)),
                ('Main_Contract_Value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('percent_Physical_Completed', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('Overall_Received_Payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Initial_Handing_Over_Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done'), ('', '')], default='', max_length=20)),
                ('Project_Finished', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('Variation_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_4', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_5', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_6', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Variation_7', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_4', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_5', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_6', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_7', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_8', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_9', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_10', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_11', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_12', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_13', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Payment_14', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Initial_Handing_Over_Letter', models.DateField(blank=True, null=True)),
                ('Initial_Handing_Over_Comments_Letter', models.TextField(blank=True, default='')),
                ('Initial_Handing_Over_Date', models.DateField(blank=True, null=True)),
                ('Final_Handing_Over_Letter', models.DateField(blank=True, null=True)),
                ('Final_Handing_Over_Comments_Letter', models.TextField(blank=True, default='')),
                ('Final_Handing_Over_Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done'), ('', '')], default='', max_length=20)),
                ('Final_Handing_Over_Date', models.DateField(blank=True, null=True)),
                ('Project_Manager', models.CharField(blank=True, choices=[('Ali', 'Ali'), ('Khalid', 'Khalid'), ('Mahmoud', 'Mahmoud'), ('Reyad', 'Reyad'), ('MEP', 'MEP'), ('Other', 'Other'), ('', '')], default='', max_length=50)),
                ('Starting_Order', models.DateField(blank=True, null=True)),
                ('Project_Duration_Days', models.IntegerField(blank=True, null=True)),
                ('Project_End_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['-Project_number'],
            },
        ),
    ]
