# Generated by Django 4.2.16 on 2026-03-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedBOQ',
            fields=[
                ('BOQ_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BOQ_Name', models.CharField(max_length=255)),
                ('Value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Comments', models.TextField(blank=True, default='')),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='boq_attachments/')),
                ('Project_number', models.ForeignKey(db_column='Project_number', on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='projects.project')),
            ],
            options={
                'db_table': 'boq_approvedboq',
                'ordering': ['BOQ_ID'],
            },
        ),
    ]
