# Generated by Django 4.2.16 on 2026-03-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date_of_submission', models.DateField(blank=True, null=True)),
                ('Certified', models.BooleanField(default=False)),
                ('Date_of_certification', models.DateField(blank=True, null=True)),
                ('Payment_Slot', models.IntegerField(blank=True, null=True)),
                ('Project_number', models.ForeignKey(db_column='Project_number', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-Payment_ID'],
            },
        ),
    ]
